spring:
  datasource:
    url: jdbc:mariadb://t7c13.p.ssafy.io:6660/test?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ssafyB101!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: debug